# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2836a433d92ea24f9977e98df209bb47"
name = "LMS"
application_url = "http://localhost:3000"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "lms-development-store-cx9qoiqw.myshopify.com"
include_config_on_deploy = true

[access_scopes]
scopes = "read_products"

[auth]
redirect_urls = [ "http://localhost:3000/api/auth/callback" ]

[webhooks]
api_version = "2025-01"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/api/webhooks"
