# LOCAL DEVELOPMENT TEMPLATE ONLY
#
# For production deployment, use:
#   shopify.app.lms.toml
#
# Deploy Shopify config with:
#   shopify app deploy -c lms --allow-updates
#
# Learn more: https://shopify.dev/docs/apps/tools/cli/configuration

name = "Shopify LMS"
client_id = "YOUR_CLIENT_ID"
application_url = "https://YOUR_APP_URL"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "YOUR_DEV_STORE.myshopify.com"

[access_scopes]
scopes = "read_products"

[auth]
redirect_urls = [
  "https://YOUR_APP_URL/api/auth/callback",
  "http://localhost:3000/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/api/webhooks"
