# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2836a433d92ea24f9977e98df209bb47"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "LMS"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "lms-development-store-cx9qoiqw.myshopify.com"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2026-10"
